### ISSUE TITLE
eicu_oxygen_therapy.sql 

### ISSUE THREAD

**Issue by XiangBu** [nus-mornin-lab/oxygenation_kc#52]
hi, When I use postgres to run eicu_oxygen_therapy.sql, error occured : [Err] Error: Invalid INT type input syntax: "2.5"
WHERE nursingchartoffset >= -60
		AND nursingchartcelltypevallabel = 'O2 L/%'
		AND CAST(nursingChartValue AS INT8) > 0
		AND CAST(nursingChartValue AS INT8) <= 100
I guess it's because some nursingChartValue can't be converted to INT, I checked the O2 L/%, some of them are float types and I'm not sure if they're just float or wrong input because some of them are between 0 to 1. I wanna know how you handled with this. Thanks!

**Comment by willemvandenboom** [comment]
Let me try to answer both questions. Please reopen this issue if you have further questions.
- We used Google BigQuery and did not encounter the error that you mention. We have not tested our scripts with PostreSQL. Also, the code that you mention is different from ours: For instance, we do not use `CAST` but instead BigQuery's `SAFE_CAST`.

- We do not use the value of 'O2 L/%' in `eicu_oxygen_therapy.sql`. Rather, we merely check whether 'O2 L/%' is recorded. If it is, then we interpret that as a sign that oxygen therapy was being administered.

- In case of seemingly wrong input, we tried to correct it or ignored the values. For instance, FiO2 is sometimes recorded between 0 and 1, and sometimes between between 0 and 100. We take this into account here: https://github.com/nus-mornin-lab/oxygenation_kc/blob/7ba234b12e9348d478cd291822c5ac328d63448c/data-extraction/eICU/eicu_oxygen_therapy.sql#L225-L246
