### ISSUE TITLE
eicu_oxygen_therapy.sql not working

### ISSUE THREAD

**Issue by mostafaalishahi** [nus-mornin-lab/oxygenation_kc#53]
I tried running the script to extract MV duration from the eICU dataset but the script seems to break for some reason.
I was wondering if you have an updated version of the script or can provide some information regarding the version of the PostgreSQL that you used?

`SQL Error [22P02]: ERROR: invalid input syntax for type double precision: "50%"`

**Comment by willemvandenboom** [comment]
I am sorry to hear that you have trouble using our script. We used Google BigQuery instead of PostgreSQL. We do not have an updated version of the script.

**Comment by mostafaalishahi** [comment]
Great 👍 , thanks a lot.
